### PR TITLE
Add SQL:2023 non-static method invocation

### PR DESCRIPTION
**Pull request by martint**
## Description

SQL:2023 specifies `<method invocation>` — `expr.method(args)` — as a sibling of
`<static method invocation>`. Where `T::method(args)` namespaces a function under a
type, `expr.method(args)` dispatches on the receiver's type and passes it as the
implicit self argument.

This change introduces the syntax and a new `@InstanceMethod` SPI annotation.
Functions tagged with `@InstanceMethod` register with a receiver type taken from
their first `@SqlType` parameter and become callable only as `expr.method(args)`.
A plain `method(args)` call cannot resolve to an instance method, mirroring the
static-method namespace separation introduced in #29385.

The receiver expression form `(expr).method(args)` parses unambiguously as a method
call. The bare `A.B(args)` form (where `A` is in scope as a column) keeps parsing
as a routine invocation, but per SQL:2023 6.3 Syntax Rule 2 the analyzer treats it
as a method invocation when one applies, falling back to function resolution
otherwise.

Example:

    @ScalarFunction("char_length")
    @InstanceMethod
    @SqlType(StandardTypes.BIGINT)
    public static long varcharCharLength(@SqlType(StandardTypes.VARCHAR) Slice self) { ... }

    SELECT 'hello'.char_length();                            -- 5
    SELECT s.char_length() FROM (VALUES VARCHAR 'hi') t(s);    -- 2

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```
# SPI
* Add `@InstanceMethod` annotation to register a scalar function as a non-static
  method of its receiver type, invocable via `expr.method(args)`.
```

### CODE REVIEW

File: core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java [hunk 1]
```diff
@@ -1460,6 +1475,122 @@ else if (isAggregation) {
...
+            if (arguments.size() + 1 > 127) {
+                throw semanticException(TOO_MANY_ARGUMENTS, node, "Too many arguments for method call .%s()", methodName);
+            }
+
+            BoundSignature signature = resolution.function().signature();
+            Type expectedReceiverType = signature.getArgumentTypes().getFirst();
+            coerceType(receiver, receiverType, expectedReceiverType, format("Method .%s receiver", methodName));
+            for (int i = 0; i < arguments.size(); i++) {
+                Expression expression = arguments.get(i);
+                Type expectedType = signature.getArgumentTypes().get(i + 1);
```
Comment (kasiafi) [inline core/trino-main/src/main/java/io/trino/sql/analyzer/ExpressionAnalyzer.java:1579]: Add a comment explaining why the type of argument #i is compared with signature argument type #i+1

File: core/trino-main/src/test/java/io/trino/operator/scalar/TestMethodCall.java [hunk 2]
```diff
@@ -0,0 +1,119 @@
...
+
+import static io.trino.spi.StandardErrorCode.FUNCTION_NOT_FOUND;
+import static io.trino.testing.assertions.TrinoExceptionAssert.assertTrinoExceptionThrownBy;
+import static org.assertj.core.api.Assertions.assertThat;
+import static org.junit.jupiter.api.TestInstance.Lifecycle.PER_CLASS;
+import static org.junit.jupiter.api.parallel.ExecutionMode.CONCURRENT;
+
+@TestInstance(PER_CLASS)
+@Execution(CONCURRENT)
+public class TestMethodCall
```
Comment (kasiafi) [inline core/trino-main/src/test/java/io/trino/operator/scalar/TestMethodCall.java:40]: Add a test where you try to invoke a non-static method in a static method manner and vice versa.

Comment (kasiafi) [inline core/trino-main/src/test/java/io/trino/operator/scalar/TestMethodCall.java:40]: Add tests with type coercion of 
- receiver (including if the function will resolve)
- arguments.

Comment (kasiafi) [inline core/trino-main/src/test/java/io/trino/operator/scalar/TestMethodCall.java:40]: Add a test with wrong definition, for example
- @InstanceMethod without @ScalarFunction
- @InstanceMethod without the `self` parameter

Comment (kasiafi) [inline core/trino-main/src/test/java/io/trino/operator/scalar/TestMethodCall.java:40]: Test case-insensitivity of name resolution.

**Review by kasiafi — APPROVED** [review]

File: core/trino-main/src/test/java/io/trino/operator/scalar/TestMethodCall.java (hunk 2 above)
Comment (martint) [reply core/trino-main/src/test/java/io/trino/operator/scalar/TestMethodCall.java:40]: Done. The `@InstanceMethod` without `@ScalarFunction` case is caught earlier by the existing "method annotated with @SqlType is missing @ScalarFunction or @ScalarOperator" check in `ScalarFromAnnotationsParser`, so the test asserts that error message. The missing-`self` case exercises the new check in `ParametricScalar`.

**Comment by electrum** [comment]
Why does the literal version require parenthesis? That seems backwards, as the literal version can't be a qualified function call (so it must be a method call), but `A.B()` could be either a method call or a schema qualified function call.

**Comment by martint** [comment]
Good catch. The example is misleading (older one that slipped through). The grammar already accepts `'hello'.length()` bare. The only literals that actually need parens are numeric ones because of lexing rules (`1.` lexes as a `DECIMAL_VALUE`). I'll fix the PR description.
