### ISSUE TITLE
Phoenix 5.0 support

### ISSUE THREAD

**Issue by yixin19** [trinodb/trino#1271]
I've tried pheonix5.0. I've replaced the phoenix embbeded driver by the new driver.
It's still not working.
It is not working, it throws Exception.
I want to know if we have some plan to have phoenix5.x supported.
Thanks!

**Comment by yixin19** [comment]
for phoenix 5.0 hbase 2.0

**Comment by jesinity** [comment]
well for class compilation only it is required just a single line change, but phoenix 5.0.0 brings hadoop 3.X and HBase 2.X.
I tried implementing the change but the maven enforcer plugin complained a lot.
So overall here it is a matter of understanding the dependencies issue.

Is it fine to :
* fix small code issue
* add the phoenix 5.0 dependency in a maven profile
* exclude all the dependencies that cause trouble
?

if so I can issue a merge request

**Comment by kokosing** [comment]
> if so I can issue a merge request

Please do.

**Comment by findepi** [comment]
cc @vincentpoon

**Comment by electrum** [comment]
My understanding is that the Phoenix project created a shaded artifact specifically for Presto. Did something cause that to become unusable?

**Comment by jesinity** [comment]
Ah, that's why the phoenix plugin has the "embedded" classifier.

The presto-phoenix connector plugin works fine, only it not compatible with newer versions of Phoenix (5.0) that rely on HBase 2.X (and Hadoop 3.X I guess).
BTW, unfortunately, Phoenix 4.14 is not supported by Hortonworks platform release 2.X, which is still stuck on Phoenix 4.7 (that does not even provide a `phoenix-client` artifact).

So overall I think support for Phoenix 5.x should be provided (at least if possible as maven profile).

**Comment by jesinity** [comment]
here is a WIP branch:

https://github.com/jesinity/presto/tree/phoenix5

`mvn clean install -Dphoenix5=true`

The code changes are minimal, but not retro compatible.
The tests compile but do not run, and here come the tears.

`
Caused by: java.io.FileNotFoundException: META-INF/native/liborg_apache_hbase_thirdparty_org.apache.phoenix.shaded.netty_transport_native_epoll_x86_64.so
	at org.apache.hbase.thirdparty.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:161)
	... 65 more
	Suppressed: java.lang.UnsatisfiedLinkError: no org_apache_hbase_thirdparty_org.apache.phoenix.shaded.netty_transport_native_epoll_x86_64 in java.library.path
		at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
		at java.lang.Runtime.loadLibrary0(Runtime.java:870)
		at java.lang.System.loadLibrary(System.java:1122)
		at org.apache.hbase.thirdparty.io.netty.util.internal.NativeLibraryUtil.loadLibrary(NativeLibraryUtil.java:38)
		at org.apache.hbase.thirdparty.io.netty.util.internal.NativeLibraryLoader.loadLibrary(NativeLibraryLoader.java:243)
		at org.apache.hbase.thirdparty.io.netty.util.internal.NativeLibraryLoader.load(NativeLibraryLoader.java:124)
		... 65 more
`

This look familiar to the issue:

https://issues.apache.org/jira/plugins/servlet/mobile#issue/HBASE-18663

I tried to force the LD_LIBRARY_PATH and I overcome this error, but then I got weird errors about HBase server test jars.
Actually HBase 2.0 has shaded netty, and Phoenix has shaded HBase server (plus the HBase server test jar) and this double shading causes classpath issues.

**Comment by yixin19** [comment]
I applied this patch to phoenix 5.0 which created a file: phoenix-client-5.0.0-HBase-2.0-embedded.jar.
After added this file to presto installation, it throws exception when start presto server.

[phoenix-5.0.0-HBase-2.0.wip.patch.txt](https://github.com/prestosql/presto/files/3779191/phoenix-5.0.0-HBase-2.0.wip.patch.txt)
[PHOENIX-5213-5.0.0-HBase-2.0.patch.txt](https://github.com/prestosql/presto/files/3779201/PHOENIX-5213-5.0.0-HBase-2.0.patch.txt)


2019-08-15T00:52:43.627+0200    INFO    main    io.prestosql.metadata.StaticCatalogStore    -- Loading catalog etc/catalog/phoenix.properties --
2019-08-15T00:52:43.737+0200    ERROR    main    io.prestosql.server.PrestoServer    java.lang.NoSuchMethodError: javax.validation.BootstrapConfiguration.getClockProviderClassName()Ljava/lang/String;
java.lang.BootstrapMethodError: java.lang.NoSuchMethodError: javax.validation.BootstrapConfiguration.getClockProviderClassName()Ljava/lang/String;
    at org.apache.bval.jsr.ConfigurationImpl.performBootstrapOverrides(ConfigurationImpl.java:454)
    at org.apache.bval.jsr.ConfigurationImpl.applyBootstrapConfiguration(ConfigurationImpl.java:444)
    at org.apache.bval.jsr.ConfigurationImpl.prepare(ConfigurationImpl.java:408)
    at org.apache.bval.jsr.ConfigurationImpl.__privileged_doBuildValidatorFactory(ConfigurationImpl.java:401)
    at org.apache.bval.jsr.ConfigurationImpl.doBuildValidatorFactory(ConfigurationImpl.java)
    at org.apache.bval.jsr.ConfigurationImpl.buildValidatorFactory(ConfigurationImpl.java:338)
    at io.airlift.configuration.ConfigurationFactory.<clinit>(ConfigurationFactory.java:82)
    at io.airlift.bootstrap.Bootstrap.initialize(Bootstrap.java:188)
    at io.prestosql.plugin.phoenix.PhoenixConnectorFactory.create(PhoenixConnectorFactory.java:72)
    at io.prestosql.connector.ConnectorManager.createConnector(ConnectorManager.java:328)
    at io.prestosql.connector.ConnectorManager.addCatalogConnector(ConnectorManager.java:198)
    at io.prestosql.connector.ConnectorManager.createConnection(ConnectorManager.java:190)
    at io.prestosql.connector.ConnectorManager.createConnection(ConnectorManager.java:176)
    at io.prestosql.metadata.StaticCatalogStore.loadCatalog(StaticCatalogStore.java:88)
    at io.prestosql.metadata.StaticCatalogStore.loadCatalogs(StaticCatalogStore.java:68)
    at io.prestosql.server.PrestoServer.run(PrestoServer.java:127)
    at io.prestosql.server.PrestoServer.main(PrestoServer.java:70)
Caused by: java.lang.NoSuchMethodError: javax.validation.BootstrapConfiguration.getClockProviderClassName()Ljava/lang/String;
    at java.lang.invoke.MethodHandleNatives.resolve(Native Method)
    at java.lang.invoke.MemberName$Factory.resolve(MemberName.java:975)
    at java.lang.invoke.MemberName$Factory.resolveOrFail(MemberName.java:1000)
    at java.lang.invoke.MethodHandles$Lookup.resolveOrFail(MethodHandles.java:1394)
    at java.lang.invoke.MethodHandles$Lookup.linkMethodHandleConstant(MethodHandles.java:1750)
    at java.lang.invoke.MethodHandleNatives.linkMethodHandleConstant(MethodHandleNatives.java:477)
    ... 17 more

**Comment by electrum** [comment]
It looks like the Phoenix project stopped producing the `embedded` classifier version starting with 4.14.2. @vincentpoon do you know anything about this?

**Comment by Naitreey** [comment]
Hi, any update on phoenix 5.0 support?

**Comment by umartin67** [comment]
I'm also curious if there's any updates to support 5.0

**Comment by toriycn** [comment]
i have the same issue too; @umartin67  did you resolve the problem ?

**Comment by lhofhansl** [comment]
Hi all... I recently got this all to work with Phoenix 5.1.0-SNAPSHOT (the Phoenix master branch) and HBase 2.2.5. I spent way too much time with this, but now it's working.

I had to patch Phoenix (master branch):
[phoenix-5.1.txt](https://github.com/prestosql/presto/files/5099880/phoenix-5.1.txt)

And Presto (also master branch):
[presto-phoenix-5.1.txt](https://github.com/prestosql/presto/files/5099881/presto-phoenix-5.1.txt)

To work around the native libraries I just configured the test to not use native epolling in io.netty - which is better for a tests anyway.

Due to Phoenix 5.x requiring Hadoop 3, but HBase 2 releasing only artifacts based on Hadoop 2, you'll have to build HBase as well and install into your local maven repo.

Since the presto-phoenix connector uses Phoenix' MapReduce integration as interface, the Hadoop and HBase version need to match exactly.

```
HBase:
$ git checkout rel/2.2.5
$ mvn -DskipTests -Dhadoop.profile=3.0 install assembly:single

Phoenix:
$ git checkout master
$ mvn -DskipTests install -Dhbase.profile=2.2
```

Not ideal.

**Comment by lhofhansl** [comment]
Phoenix 5.0.x should be similar.

**Comment by lhofhansl** [comment]
I create a ticket for the Phoenix change.

@electrum the 4.14.1 client works with all later 4.x versions of Phoenix.
Phoenix 5.0.0 was released before we had the embedded client, so the next version would 5.1.0.

Unfortunately Phoenix 5.x has stalled a little. The 5.0.0 release was two years ago and no release since, as some bigger changes are making it in; and the focus was on the 4.x branches - no excuse, though. There's renewed drive now for 5.1.0.

**Comment by lhofhansl** [comment]
Update of the old issue, just in case someone is interested...
The phoenix patch is not longer needed.

Here's a update patch for trino.
[trino-phoenix-5.1.txt](https://github.com/trinodb/trino/files/5799394/trino-phoenix-5.1.txt)

The build instructions are the same above. I.e.:
```
HBase:
$ git checkout rel/2.2.5
$ mvn -DskipTests -Dhadoop.profile=3.0 install assembly:single

Phoenix:
$ git checkout master
$ mvn -DskipTests install -Dhbase.profile=2.2
```

The build trino again the local maven repo.

And, no, there is still no Phoenix 5.1 release. :(
