### ISSUE TITLE
Hive 4.x+ support

### ISSUE THREAD

**Issue by jameno123** [trinodb/trino#15560]
It seems that currently hive 3.1 does not support Hadoop 3.3, and hadoop 3.3 only seems to be supported by Hive 4.x.

While attempting to get trino to work with hadoop-3.3  we ran into a road-block with hive metastore.

I tried to:
1. change the trino-hive-apache pom.xml to utilize hive 4.0.0-alpha-2 and hadoop-3.3.4 
2. Change the dependancy on hive from hive-standalone-metastore to hive-standalone-metastore-common
3. Downloaded the new thrift file from hive 4.0.0-alpha-2; and placed in trino-hive-apache/src/main/thrift/hive_metastore.thrift
4. Recompile using maven

This resulted in the following error:
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.1:compile (default-compile) on project hive-apache: Compilation failure: Compilation failure: 
[ERROR] trino-hive-apache/target/generated-sources/thrift/org/apache/hadoop/hive/metastore/api/ThriftHiveMetastore.java:[8870,19] org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore.AsyncClient.setMetaConf_call is not abstract and does not override abstract method getResult() in org.apache.thrift.async.TAsyncMethodCall
[ERROR] trino-hive-apache/target/generated-sources/thrift/org/apache/hadoop/hive/metastore/api/ThriftHiveMetastore.java:[8888,19] getResult() in org.apache.hadoop.hive.metastore.api.ThriftHiveMetastore.AsyncClient.setMetaConf_call cannot override getResult() in org.apache.thrift.async.TAsyncMethodCall
[ERROR]   return type void is not compatible with java.lang.Object

Is there any plan to support hive 4.x in trino to gain support for hadoop 3.3?
