### PR TITLE
Add more properties to Iceberg $properties result

### LINKED ISSUE #24812: Add more properties to Iceberg `$properties` result
Trino:
```sql
CREATE TABLE test_iceberg AS SELECT 1 a;
TABLE "test_iceberg$properties";
               key               |  value
---------------------------------+---------
 write.format.default            | PARQUET
 write.parquet.compression-codec | zstd
(2 rows)
```

Spark:
```sql
SHOW TBLPROPERTIES default.test_iceberg;
current-snapshot-id	6491217016127971415
format	iceberg/PARQUET
format-version	2
write.format.default	PARQUET
write.parquet.compression-codec	zstd
Time taken: 0.034 seconds, Fetched 5 row(s)
```

The relevant class is [PropertiesTable](https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PropertiesTable.java). The test class is [BaseIcebergSystemTables](https://github.com/trinodb/trino/blob/master/plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java). 

Spark implementation is probably [SparkTable#properties](https://github.com/apache/iceberg/blob/af00d1fb13a89c8e9684c097d3ece9b05ed302bb/spark/v3.5/spark/src/main/java/org/apache/iceberg/spark/source/SparkTable.java#L212-L249) method.

### PR DESCRIPTION
**Pull request by ozakidai**
## Description

Added more properties to Iceberg $properties result for #24812

## Additional context and related issues

Fixes #24812

## Example

```
TABLE "test_iceberg$properties";
               key               |                                               value                                           
---------------------------------+-----------------------------------------------------------------------------------------------
 format                          | iceberg/PARQUET                                                                               
 current-snapshot-id             | 47266285455662362                                                                             
 location                        | s3://bucket/path/
 format-version                  | 2                                                                                             
 write.format.default            | PARQUET                                                                                       
 write.parquet.compression-codec | zstd    
```

## Release notes

(x) This is not user-visible or is docs only, and no release notes are required.

### CODE REVIEW

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PropertiesTable.java [hunk 1]
```diff
@@ -67,11 +83,25 @@ public ConnectorPageSource pageSource(ConnectorTransactionHandle transactionHand
...
     }
 
-    private static List<Page> buildPages(ConnectorTableMetadata tableMetadata, Table icebergTable)
+    private static List<Page> buildPages(ConnectorTableMetadata tableMetadata, BaseTable icebergTable)
     {
-        PageListBuilder pagesBuilder = PageListBuilder.forTable(tableMetadata);
+        ImmutableMap.Builder<String, String> properties = ImmutableMap.builder();
+        String currentSnapshotId = icebergTable.currentSnapshot() != null ? String.valueOf(icebergTable.currentSnapshot().snapshotId()) : "none";
+        String fileFormat = icebergTable.properties().getOrDefault(DEFAULT_FILE_FORMAT, DEFAULT_FILE_FORMAT_DEFAULT);
+        properties.put("format", "iceberg/" + fileFormat);
```
Comment (chenjian2664) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PropertiesTable.java:91]: Would it be useful that add the fixed key as column metadata to tableMetadata?  cc @ebyhr

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PropertiesTable.java [hunk 2]
```diff
@@ -67,11 +83,25 @@ public ConnectorPageSource pageSource(ConnectorTransactionHandle transactionHand
...
+        if (!icebergTable.sortOrder().isUnsorted()) {
+            properties.put("sort-order", describeSortOrder(icebergTable.sortOrder()));
+        }
+        icebergTable.properties().entrySet().stream()
+                .filter(entry -> !RESERVED_PROPERTIES.contains(entry.getKey()))
+                .forEach(properties::put);
 
-        icebergTable.properties().entrySet().forEach(prop -> {
+        PageListBuilder pagesBuilder = PageListBuilder.forTable(tableMetadata);
+        properties.buildOrThrow().entrySet().forEach(prop -> {
```
Comment (chenjian2664) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PropertiesTable.java:104]: We could use `properties.buildOrThrow().forEach((key, value) -> {`

**Review by chenjian2664 — COMMENTED** [review]
Looks good

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PropertiesTable.java (hunk 1 above)
Comment (ozakidai) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PropertiesTable.java:91]: @chenjian2664 
Thank you for reviewing my PR!
What do you mean "the fixed key"?

Comment (chenjian2664) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/PropertiesTable.java:91]: I was thought that we could define the `ColumnMetadata` that we exactly support instead just put key/value there.
But it seems that it's hard to keep the other rest properties.

File: plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java [hunk 3]
```diff
@@ -817,6 +818,31 @@ void testEntriesPartitionTable()
...
+    @Test
+    public void testPropertiesTable()
+    {
+        try (TestTable table = newTrinoTable("test_properties", "(x BIGINT,y DOUBLE) WITH (sorted_by = ARRAY['y'])")) {
+            Table icebergTable = loadTable(table.getName());
+            assertThat(getTableProperties(table.getName()))
+                    .containsExactly(
+                            entry("format", "iceberg/" + format.name()),
+                            entry("provider", "iceberg"),
+                            entry("current-snapshot-id", Long.toString(icebergTable.currentSnapshot().snapshotId())),
```
Comment (chenjian2664) [inline plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java:830]: what if the table has no snapshot, you puts the `none`, here seems not that case

Comment (ozakidai) [reply plugin/trino-iceberg/src/test/java/io/trino/plugin/iceberg/BaseIcebergSystemTables.java:830]: Thanks. Here's the updated version. Does this look better?

>            String currentSnapshotId = icebergTable.currentSnapshot() != null ? String.valueOf(icebergTable.currentSnapshot().snapshotId()) : "none";
>            assertThat(getTableProperties(table.getName()))
>                    .containsExactly(
>                            entry("format", "iceberg/" + format.name()),
>                            entry("provider", "iceberg"),
>                            entry("current-snapshot-id", currentSnapshotId),
>                            entry("location", icebergTable.location()),

File: plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java
Comment (ozakidai) [inline plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:1]: @ebyhr 

When I built the code, I got following error:
> incompatible types: org.apache.iceberg.Table cannot be converted to org.apache.iceberg.BaseTable

This change explicitly casts the Table interface to BaseTable.
>        try {
>            table = (BaseTable) catalog.loadTable(session, new SchemaTableName(tableName.getSchemaName(), name));
>        }

Comment (ebyhr) [reply plugin/trino-iceberg/src/main/java/io/trino/plugin/iceberg/IcebergMetadata.java:1]: It's a logical conflict due to https://github.com/trinodb/trino/pull/24956. Could you rebase on master?

**Comment by ebyhr** [comment]
@cla-bot check

**Review by chenjian2664 — APPROVED** [review]

**Comment by ebyhr** [comment]
Please ping me once your CLA is registered.

**Comment by ozakidai** [comment]
Thanks so much for the review! @ebyhr @chenjian2664
