### ISSUE TITLE
The requested schema is not compatible with the file schema. incompatible types

### ISSUE THREAD

**Issue by lxqfy** [trinodb/trino#9248]
SQL
`select extinfo.qris_info.merchant_account_information from extinfo_table;`
The following error occurred after upgrading from 332 to 356.
```
The requested schema is not compatible with the file schema. incompatible types: required group qris_info {
  required binary merchant_account_information (STRING);
} != optional group qris_info {
  required binary point_of_initiation_method (STRING);
  required binary merchant_account_information (STRING);
  required binary merchant_category_code (STRING);
  required binary transaction_currency (STRING);
  required binary transaction_amount (STRING);
  required binary convenience_indicator (STRING);
  required binary value_of_convenience_fee_fixed (STRING);
  required binary value_of_convenience_fee_percentage (STRING);
  required binary country_code (STRING);
  required binary merchant_name (STRING);
  required binary merchant_city (STRING);
  required binary postal_code (STRING);
  optional group additional_data_field_template {
    required binary bill_number (STRING);
    required binary mobile_number (STRING);
    required binary store_label (STRING);
    required binary loyalty_number (STRING);
    required binary reference_label (STRING);
    required binary customer_label (STRING);
    required binary terminal_label (STRING);
    required binary purpose_of_transaction (STRING);
    required binary additional_consumer_data_request (STRING);
    required group rfu_for_emvco (LIST) {
      repeated group list {
        required binary element (STRING);
      }
    }
    required group payment_system_specific_templates (LIST) {
      repeated group list {
        required binary element (STRING);
      }
    }
    required binary security (STRING);
  }
  required binary additional_data_field_raw (STRING);
  optional group merchant_information_language_template {
    required binary language_preference (STRING);
    required binary merchant_name (STRING);
    required binary merchant_city (STRING);
  }
  required binary payload_format_indicator (STRING);
}```
