### PR TITLE
Add `$partitions` table to Delta Connector

### PR DESCRIPTION
**Pull request by whitleykeith**
## Description

This PR implements the `$partitions` system table for the Delta Lake connector, and behaves similarly to the Hive analog. It additionally adds a `.devcontainer.json` to support running Trino in a devcontainer/codespace. I did this primarily for my own workflow and can remove it if it's not desired. 

An implementation wrinkle: Due to how the `AddFileEntry.getCanonicalPartitionValues` returns strings for partition values and some issues with casting back to their original types, the columns in the result table are always VARCHAR, even if the underlying column is a different type. I called this out in the related doc updates.

## Additional context and related issues
Closes https://github.com/trinodb/trino/issues/18590

## Release notes

( ) This is not user-visible or is docs only, and no release notes are required.
( ) Release notes are required. Please propose a release note for me.
(x) Release notes are required, with the following suggested text:

```markdown
# Delta Lake
* Add `$partitions` system table to the Delta Connector ({issue}`18590`)
```

### CODE REVIEW

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java [hunk 1]
```diff
@@ -0,0 +1,147 @@
...
+            TransactionLogAccess transactionLogAccess,
+            List<DeltaLakeColumnHandle> partitionColumns)
+    {
+        this.tableName = requireNonNull(tableName, "tableName is null");
+        this.tableLocation = requireNonNull(tableLocation, "tableLocation is null");
+        this.transactionLogAccess = requireNonNull(transactionLogAccess, "transactionLogAccess is null");
+        this.partitionColumns = requireNonNull(partitionColumns, "partitionColumns is null");
+
+        ImmutableList.Builder<ColumnMetadata> columns = ImmutableList.builder();
+        partitionColumns.forEach(column -> columns.add(new ColumnMetadata(column.getBaseColumnName(), VARCHAR)));
```
Comment (findinpath) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java:66]: i don't follow the reasoning behind this constraint - why not using the actual type of the partition column?

Comment (whitleykeith) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java:66]: I initially tried to do that, but there were issues with casting back to the original type as `AddFileEntry.getCanonicalPartitionValues()` returns a string represenation of the value

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java [hunk 2]
```diff
@@ -103,4 +103,85 @@ public void testPropertiesTable()
...
     }
+
+    @Test
+    public void testPartitionsTable()
+    {
+        String tableName = "test_simple_partitions_table";
+        try {
+            assertUpdate("CREATE TABLE " + tableName + " (_bigint BIGINT, _date DATE) WITH (partitioned_by = ARRAY['_date'] )");
+            assertUpdate("INSERT INTO " + tableName + " VALUES (0, CAST('2019-09-08' AS DATE)), (1, CAST('2019-09-09' AS DATE)), (2, CAST('2019-09-09' AS DATE))", 3);
+            assertUpdate("INSERT INTO " + tableName + " VALUES (3, CAST('2019-09-09' AS DATE)), (4, CAST('2019-09-10' AS DATE)), (5, CAST('2019-09-10' AS DATE))", 3);
```
Comment (ebyhr) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java:114]: Please test with NULL partitions.

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java [hunk 3]
```diff
@@ -103,4 +103,85 @@ public void testPropertiesTable()
...
+            assertUpdate("UPDATE " + tableName + " SET _bigint = 50 WHERE _bigint =  BIGINT '5'", 1);
+            assertUpdate("DELETE FROM " + tableName + " WHERE _date =  DATE '2019-09-08'", 1);
+            assertQuerySucceeds("ALTER TABLE " + tableName + " EXECUTE OPTIMIZE");
```
Comment (ebyhr) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java:117]: These statements reduce readability of this test. I would remove or separate a test method.

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java [hunk 4]
```diff
@@ -103,4 +103,85 @@ public void testPropertiesTable()
...
+            assertQuery("SELECT count(*) FROM " + tableName, "VALUES 5");
+            assertQuery("SELECT count(*) FROM \"" + tableName + "$partitions\"", "VALUES 2");
+
+            assertQuery("SHOW COLUMNS FROM \"" + tableName + "$partitions\"",
+                    """
+                            VALUES
+                            ('_date', 'varchar', '', '')
+                            """);
+
+            // Test the contents of partitions system table
```
Comment (ebyhr) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java:127]: 👍 Please verify the result in this PR, not follow-up.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTableProvider.java [hunk 5]
```diff
@@ -0,0 +1,65 @@
...
+import io.trino.spi.TrinoException;
+import io.trino.spi.connector.ConnectorSession;
+import io.trino.spi.connector.SchemaTableName;
+import io.trino.spi.type.TypeManager;
+
+import java.io.IOException;
+import java.util.List;
+import java.util.Optional;
+
+public class DeltaLakePartitionsTableProvider
```
Comment (ebyhr) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTableProvider.java:29]: I would merge into DeltaLakePartitionsTable.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTableProvider.java [hunk 6]
```diff
@@ -0,0 +1,65 @@
...
+    {
+        try {
+            // Verify the transaction log is readable
+            SchemaTableName baseTableName = new SchemaTableName(tableName.getSchemaName(), DeltaLakeTableName.tableNameFrom(tableName.getTableName()));
+            TableSnapshot tableSnapshot = transactionLogAccess.getSnapshot(session, baseTableName, tableLocation, Optional.empty());
+            MetadataEntry metadata = transactionLogAccess.getMetadataEntry(tableSnapshot, session);
+            return DeltaLakeSchemaSupport.extractPartitionColumns(metadata, transactionLogAccess.getProtocolEntry(session, tableSnapshot), typeManager);
+        }
+        catch (IOException e) {
+            throw new TrinoException(DeltaLakeErrorCode.DELTA_LAKE_INVALID_SCHEMA, "Unable to load table metadata from location: " + tableLocation, e);
```
Comment (ebyhr) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTableProvider.java:62]: Static import `DELTA_LAKE_INVALID_SCHEMA`.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTableProvider.java [hunk 7]
```diff
@@ -0,0 +1,65 @@
...
+    }
+
+    public List<DeltaLakeColumnHandle> getPartitionColumns(SchemaTableName tableName, String tableLocation, ConnectorSession session)
+    {
+        try {
+            // Verify the transaction log is readable
+            SchemaTableName baseTableName = new SchemaTableName(tableName.getSchemaName(), DeltaLakeTableName.tableNameFrom(tableName.getTableName()));
+            TableSnapshot tableSnapshot = transactionLogAccess.getSnapshot(session, baseTableName, tableLocation, Optional.empty());
+            MetadataEntry metadata = transactionLogAccess.getMetadataEntry(tableSnapshot, session);
+            return DeltaLakeSchemaSupport.extractPartitionColumns(metadata, transactionLogAccess.getProtocolEntry(session, tableSnapshot), typeManager);
```
Comment (ebyhr) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTableProvider.java:59]: Static import `extractPartitionColumns` method.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java [hunk 8]
```diff
@@ -0,0 +1,147 @@
...
+
+        this.tableMetadata = new ConnectorTableMetadata(
+                requireNonNull(tableName, "tableName is null"),
+                columns.build());
```
Comment (ebyhr) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java:70]: Remove redundant `requireNonNull` and unwrap lines.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java (hunk 1 above)
Comment (ebyhr) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java:66]: It should be the original type. Also, we need to discuss the result columns (Hive or Iceberg)
```sql
-- Hive
select * from "test$partitions";
 b
---
 1

-- Iceberg
select * from "test$partitions";
 partition | record_count | file_count | total_size |                       data
-----------+--------------+------------+------------+--------------------------------------------------
 {b=1}     |            1 |          1 |        317 | {a={min=1, max=1, null_count=0, nan_count=NULL}}
```

Comment (ebyhr) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java:66]: No need to define the variable as builder. e.g.
```java
        List<ColumnMetadata> columns = partitionColumns.stream()
                .map(column -> new ColumnMetadata(column.getBaseColumnName(), VARCHAR))
                .collect(toImmutableList());
```

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java [hunk 9]
```diff
@@ -0,0 +1,147 @@
...
+    public DeltaLakePartitionsTable(
+            SchemaTableName tableName,
+            String tableLocation,
+            TransactionLogAccess transactionLogAccess,
+            List<DeltaLakeColumnHandle> partitionColumns)
+    {
+        this.tableName = requireNonNull(tableName, "tableName is null");
+        this.tableLocation = requireNonNull(tableLocation, "tableLocation is null");
+        this.transactionLogAccess = requireNonNull(transactionLogAccess, "transactionLogAccess is null");
+        this.partitionColumns = requireNonNull(partitionColumns, "partitionColumns is null");
```
Comment (ebyhr) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java:63]: Add `ImmutableList.copyOf`.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java [hunk 10]
```diff
@@ -0,0 +1,147 @@
...
+                    "Unable to load table metadata from location: " + tableLocation, e);
+        }
+        if (partitionColumns.isEmpty()) {
+            return new EmptyPageSource();
+        }
+        return new FixedPageSource(buildPages(session, tableSnapshot, metadataEntry, constraint));
+    }
+
+    private List<Page> buildPages(ConnectorSession session, TableSnapshot tableSnapshot, MetadataEntry metadataEntry,
+            TupleDomain<Integer> constraint)
```
Comment (ebyhr) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java:109]: Remove unused `TupleDomain<Integer> constraint`.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java [hunk 11]
```diff
@@ -0,0 +1,147 @@
...
+        for (Map<String, Optional<String>> partitionValue : getDedupedPartitionValues(activeFiles)) {
+            if (partitionValue.isEmpty()) {
+                pageListBuilder.beginRow();
+                pageListBuilder.appendNull();
+                pageListBuilder.endRow();
+                continue;
+            }
+
+            pageListBuilder.beginRow();
+            for (int i = 0; i < partitionColumns.size(); i++) {
```
Comment (ebyhr) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java:125]: Replace with enhanced 'for'.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java [hunk 12]
```diff
@@ -0,0 +1,147 @@
...
+        MetadataEntry metadataEntry;
+        try {
+            // Verify the transaction log is readable
+            SchemaTableName baseTableName = new SchemaTableName(tableName.getSchemaName(),
+                    DeltaLakeTableName.tableNameFrom(tableName.getTableName()));
+            tableSnapshot = transactionLogAccess.getSnapshot(session, baseTableName, tableLocation, Optional.empty());
+            metadataEntry = transactionLogAccess.getMetadataEntry(tableSnapshot, session);
+        }
+        catch (IOException e) {
+            throw new TrinoException(DeltaLakeErrorCode.DELTA_LAKE_INVALID_SCHEMA,
```
Comment (ebyhr) [inline plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java:99]: Static import `DELTA_LAKE_INVALID_SCHEMA`.

File: docs/src/main/sphinx/connector/delta-lake.md [hunk 13]
```diff
@@ -704,6 +704,49 @@ delta.feature.columnMapping | supported       |
...
+Will return the following:
+
+```text
+regionkey                  |
+---------------------------+
+east                       |
+west                       |
+```
+
+>Note: The types of columns in the `$partitions` table are always VARCHAR, even if the underlying column is a different type.
```
Comment (ebyhr) [inline docs/src/main/sphinx/connector/delta-lake.md:748]: Remove this note. The implementation should be fixed.

File: .devcontainer/devcontainer.json [hunk 14]
```diff
@@ -0,0 +1,18 @@
+{
```
Comment (ebyhr) [inline .devcontainer/devcontainer.json:1]: Please **_rebase_** on master instead of **_merge_** and fix logical conflicts. 
```
Error:  Failed to execute goal org.apache.maven.plugins:maven-compiler-plugin:3.11.0:compile (default-compile) on project trino-delta-lake: Compilation failure: Compilation failure: 
Error:  /home/runner/work/trino/trino/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java:[95,49] cannot find symbol
Error:    symbol:   method getSnapshot(io.trino.spi.connector.ConnectorSession,io.trino.spi.connector.SchemaTableName,java.lang.String,java.util.Optional<java.lang.Object>)
Error:    location: variable transactionLogAccess of type io.trino.plugin.deltalake.transactionlog.TransactionLogAccess
Error:  /home/runner/work/trino/trino/plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTableProvider.java:[57,63] cannot find symbol
Error:    symbol:   method getSnapshot(io.trino.spi.connector.ConnectorSession,io.trino.spi.connector.SchemaTableName,java.lang.String,java.util.Optional<java.lang.Object>)
Error:    location: variable transactionLogAccess of type io.trino.plugin.deltalake.transactionlog.TransactionLogAccess
Error:  -> [Help 1]
```

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java [hunk 15]
```diff
@@ -103,4 +103,85 @@ public void testPropertiesTable()
             assertUpdate("DROP TABLE IF EXISTS " + tableName);
         }
     }
+
+    @Test
+    public void testPartitionsTable()
+    {
+        String tableName = "test_simple_partitions_table";
```
Comment (ebyhr) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java:110]: All 3 tests have `_simple_` in the table name. It doesn't provide any benefits unless we have complex tests. I would remove them.

File: plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java [hunk 16]
```diff
@@ -103,4 +103,85 @@ public void testPropertiesTable()
...
+        String tableName = "test_simple_partitions_table_unpartitioned";
+        try {
+            assertUpdate("CREATE TABLE " + tableName + " (_bigint BIGINT, _date DATE)");
+            assertUpdate("INSERT INTO " + tableName + " VALUES (0, CAST('2019-09-08' AS DATE)), (1, CAST('2019-09-09' AS DATE)), (2, CAST('2019-09-09' AS DATE))", 3);
+            assertUpdate("INSERT INTO " + tableName + " VALUES (3, CAST('2019-09-09' AS DATE)), (4, CAST('2019-09-10' AS DATE)), (5, CAST('2019-09-10' AS DATE))", 3);
+            assertUpdate("UPDATE " + tableName + " SET _bigint = 50 WHERE _bigint =  BIGINT '5'", 1);
+            assertUpdate("DELETE FROM " + tableName + " WHERE _date =  DATE '2019-09-08'", 1);
+            assertQuerySucceeds("ALTER TABLE " + tableName + " EXECUTE OPTIMIZE");
+            assertQuery("SELECT count(*) FROM " + tableName, "VALUES 5");
+            assertQuery("SELECT count(*) FROM \"" + tableName + "$partitions\"", "VALUES 0");
```
Comment (ebyhr) [inline plugin/trino-delta-lake/src/test/java/io/trino/plugin/deltalake/TestDeltaLakeSystemTables.java:177]: I would remove these statements. Single INSERT is sufficient for verifying `$partitons` with unpartitioned table.

File: docs/src/main/sphinx/connector/delta-lake.md [hunk 17]
```diff
@@ -704,6 +704,49 @@ delta.feature.columnMapping | supported       |
 
 (delta-lake-special-columns)=
 
+#### `$partitions` table
```
Comment (ebyhr) [inline docs/src/main/sphinx/connector/delta-lake.md:707]: The current place (after `(delta-lake-special-columns)=`) is wrong.

File: docs/src/main/sphinx/connector/delta-lake.md [hunk 18]
```diff
@@ -704,6 +704,49 @@ delta.feature.columnMapping | supported       |
...
+
+The `$partitions` table provides access to a specified Delta Lake Table's partitions keys and values. Each table row is a unique partition value, with the columns being the partition keys. 
+
+For example, provided a table with the `regionkey` column set as a partition key:
+
+
```
Comment (ebyhr) [inline docs/src/main/sphinx/connector/delta-lake.md:713]: Remove a redundant empty line.

File: plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java (hunk 1 above)
Comment (whitleykeith) [reply plugin/trino-delta-lake/src/main/java/io/trino/plugin/deltalake/DeltaLakePartitionsTable.java:66]: I'll try to see if I can get the types correct 👍 

Good point on format, I've only used the `hive` and `delta` connectors in practice so went with the original Hive format. The Iceberg format has a lot more info, but I'm not sure how best to materialize that from the transaction log.

**Comment by mosabua** [comment]
:wave: @whitleykeith - this PR has become inactive. If you're still interested in working on it, please let us know, and we can try to get reviewers to help with that.

We're working on closing out old and inactive PRs, so if you're too busy or this has too many merge conflicts to be worth picking back up, we'll be making another pass to close it out in a few weeks.

**Comment by mosabua** [comment]
@findinpath @ebyhr .. is this still useful/valid or should we close?

**Comment by whitleykeith** [comment]
@mosabua I'm the original author of the PR. Sorry for not chiming in here, I chatted with @findinpath last month in slack about this. We use Trino a lot, especially the Delta connector, and I would love to be able to get this in a good state. I ran out of time when I first started development on this but I'm hoping I can block off some time in the next few weeks to resolve comments + make necessary changes

**Comment by mosabua** [comment]
Thats great news @whitleykeith .. feel free to continue to work with @findinpath and others and let me know if you need any other help.

**Comment by whitleykeith** [comment]
It was easier to make a brand new PR since there was a lot of changes (including a java version upgrade), new PR is here: https://github.com/trinodb/trino/pull/20735
